version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql 
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql1234
      MYSQL_DATABASE: inventario
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword1234
    ports:
      - 3306:3306